# Spring properties
spring:
  application:
    name: product-service

# HTTP Server
server:
  port: 8080



# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://54.174.213.54:8080/discovery-server/eureka/
    instance:
      leaseRenewalIntervalInSeconds: false   # DO NOT DO THIS IN PRODUCTION

management:
  security:
    enabled: false

#http://54.174.213.54:8080/product-service/swagger-ui.html
#http://54.174.213.54:8080/product-service/actuator/info
