# Spring properties
spring:
  application:
    name: product-service

# HTTP Server
server:
  port: 9090
  servlet:
      context-path: /product-service


# Discovery Server Access
eureka:
  client:
    serviceUrl:
                  defaultZone: http://134.209.96.223:8080/discovery-server/eureka/
    instance:
      leaseRenewalIntervalInSeconds: false   # DO NOT DO THIS IN PRODUCTION

management:
  security:
    enabled: false



#http://localhost:2222/product-service/swagger-ui.html#/
#http://localhost:2222/product-service/products/


