# Spring properties
spring:
  application:
    name: product-service

# HTTP Server
server:
  port: 9090
  servlet:
      context-path: /product-service

my_message: server 9090


#  eureka.instance.prefer-ip-address=true
#  eureka.instance.ip-address=
# Discovery Server Access
eureka:
  instance:
    prefer-ip-address : true
    ip-address : 134.209.96.223
  client:
    serviceUrl:
                  defaultZone: http://134.209.96.223:8761/discovery-server/eureka/
    instance:
      leaseRenewalIntervalInSeconds: false   # DO NOT DO THIS IN PRODUCTION

management:
  security:
    enabled: false



#http://localhost:2222/product-service/swagger-ui.html#/
#http://localhost:2222/product-service/products/


