# Spring properties
spring:
  application:
    name: user-service
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.0.101:3406/user_service
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: create
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    database: mysql

# HTTP Server
server:
  port: 9090
  servlet:
    context-path: /user-service

my_message: server 9090


#  eureka.instance.prefer-ip-address=true
#  eureka.instance.ip-address=
# Discovery Server Access
eureka:
  instance:
    prefer-ip-address: true
    ip-address: localhost
  client:
    serviceUrl:
      defaultZone: http://192.168.0.101:8080/discovery-server/eureka/
    #                  defaultZone: http://localhost:8761/discovery-server/eureka/
    instance:
      leaseRenewalIntervalInSeconds: false   # DO NOT DO THIS IN PRODUCTION

management:
  security:
    enabled: false



#http://localhost:9090/user-service/swagger-ui.html#/


